[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.vesktop]
input_path = './templates/matugen-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.Obsidian]
input_path = './templates/obisidan-colors.css'
output_path = '~/Documents/vault/.obsidian/snippets/colors.css'
